### ISSUE TITLE
Add CLI (Info and Grid)

### ISSUE THREAD

**Issue by vincentsarago** [geospatial-jeff/aiocogeo#16]
I think it will be good to have a CLI with this tool. 
Right now I'm think about 
- Info: dump general info about the COG (https://github.com/blacha/cogeotiff#cogeotiff-info)
    - blocks
    - size
    - min/max/mean block size per overview
    - mask 
    - compression

- grid: return a TMS model of the internal structure of the COG (using morecantile tms model)

**Comment by geospatial-jeff** [comment]
Love it!  Everything you've listed except masks is supported by whats currently in the library.

Masks should be added soon!

**Comment by vincentsarago** [comment]
this is good to close I think
