### ISSUE TITLE
add logging 

### ISSUE THREAD

**Issue by vincentsarago** [geospatial-jeff/aiocogeo#22]
Would be really useful for debugging purposes to have more verbosity on reads. 

I often use `CPL_DEBUG` and `CPL_CURL_VERBOSE` withing GDAL to see how much data and how many GET/LIST/HEAD request gdal is doing. 

Side note: myabe having and internal variable to host this could be cool: 

```python
async with COGReader("https://async-cog-reader-test-data.s3.amazonaws.com/webp_cog.tif") as cog:
    x = y = z = 0
    tile = await cog.get_tile(x, y, z)

print(cog.requests)
{
    count: 3,   
    size: TotalSizeOfRequest
    get: [
       'offset1-offset2', sizeOfRequest1,
       'offset3-offset4',  sizeOfRequest2,
       'offset5-offset6',  sizeOfRequest3
   ]
} 
```

**Comment by geospatial-jeff** [comment]
> Side note: myabe having and internal variable to host this could be cool:

Each filesystem already tracks this ([http for example](https://github.com/geospatial-jeff/async-cog-reader/blob/master/async_cog_reader/filesystems.py#L65-L71)), but its not logged out.  big +1 for better logs.

I'm not tracking individual requests yet (just aggregate) but I can add.
