### ISSUE TITLE
Merge consecutive Requests

### ISSUE THREAD

**Issue by vincentsarago** [geospatial-jeff/aiocogeo#23]
linked to #21, GDAL merge consecutive requests (horizontal tiles, when band interleave I think) up to 2Mb (configurable).

> Partial downloads (requires the HTTP server to support random reading) are done with a 16 KB granularity by default. Starting with GDAL 2.3, the chunk size can be configured with the CPL_VSIL_CURL_CHUNK_SIZE configuration option, with a value in bytes. If the driver detects sequential reading it will progressively increase the chunk size up to 2 MB to improve download performance. Starting with GDAL 2.3, the GDAL_INGESTED_BYTES_AT_OPEN configuration option can be set to impose the number of bytes read in one GET call at file opening (can help performance to read Cloud optimized geotiff with a large header).

Ref: https://gdal.org/user/virtual_file_systems.html#virtual-file-systems

**Comment by geospatial-jeff** [comment]
For reference, I closed #21 after my initial tests for merging consecutive ranges but I was merging across rows and columns with a pretty large COG which explains why it was so slow.

Will retry with horizontal tiles/band interleave.

**Comment by geospatial-jeff** [comment]
Closed with #33
