### ISSUE TITLE
Cache only COG header

### ISSUE THREAD

**Issue by dmahr1** [geospatial-jeff/aiocogeo#82]
https://cogeotiff.slack.com/archives/C01DE57GLHE/p1603130953009500

## Summary
Consider a case where `N` unique tile requests are made to a single COG. Despite the `ENABLE_CACHE` environment variable being enabled, all requests would be cache misses. Thus at least `2 * N` range requests would need to be made to the COG. But if the COG header were cached separately, then only `1 + N` range requests would need to be made.

## Details
I plan to incorporate `aiocogeo` within a traditional tile server middleware that handles regular `z/x/y.png` requests. These currently read PNG tiles that are stored as a tile pyramid in bucket storage. This dated architecture is space inefficient but very performant. I'm hoping to achieve the space savings of COGs (via YCbCr JPEG compression + GDAL mask bands) without a meaningful increase in latency. One way to eliminate that latency is by caching the header in redis or another fast cache available to many servers. For example:
- Client requests Mercator tile `(z, x, y)` for `cog.tif` in cloud bucket storage. Networking layer routes it to COG server 1 (one of many COG servers).
  - COG server 1 checks redis (or another cache) for `cog.tif` header, but it's not found. **CACHE MISS.**
  - _COG server 1 makes range request to `cog.tif` header._
  - _COG server 1 caches `cog.tif` header in redis._
  - COG server 1 makes range request for `(z, x, y)` tile data.
  - COG server 1 performs postprocessing and returns `(z, x, y)` tile data to client.
- Client requests Mercator tile `(z, x + 1, y)` for `cog.tif` in cloud bucket storage. Networking layer routes it to COG server 2.
  - COG server 2 checks redis for `cog.tif` header and it's found. **CACHE HIT.**
  - COG server 2 makes range request for `(z, x + 1, y)` tile data.
  - COG server 2 performs postprocessing and returns `(z, x + 1, y)` tile data to client.

The two italicized operations for the first request are not necessary for the second request.

**Comment by geospatial-jeff** [comment]
This was implemented in https://github.com/geospatial-jeff/aiocogeo/pull/90, will be included in the next release!

**Comment by dmahr1** [comment]
Amazing! You're a hero, @geospatial-jeff. I was planning to play around with this over the holidays but you beat me to it!
